apiVersion: v1
kind: ConfigMap
metadata:
 name: flask-config
data:
 POSTGRES_HOST: postgres
 POSTGRES_DB: {{ .Values.postgres.database | quote }}
 POSTGRES_USER: {{ .Values.postgres.username | quote }}
