apiVersion: v1
kind: ConfigMap
metadata:
 name: postgres-init
data:
 init.sql: | 
  CREATE TABLE users (
   id SERIAL PRIMARY KEY,
   name TEXT NOT NULL
  );

  INSERT INTO users (name)
  VALUES ('Kubernetes User');
